/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWalletsRouteImport } from './routes/_authenticated/app.wallets'
import { Route as AuthenticatedAppTransactionsRouteImport } from './routes/_authenticated/app.transactions'
import { Route as AuthenticatedAppGoalsRouteImport } from './routes/_authenticated/app.goals'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/app.coach'
import { Route as AuthenticatedAppBudgetsRouteImport } from './routes/_authenticated/app.budgets'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWalletsRoute = AuthenticatedAppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGoalsRoute = AuthenticatedAppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBudgetsRoute = AuthenticatedAppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/budgets': typeof AuthenticatedAppBudgetsRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/goals': typeof AuthenticatedAppGoalsRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/wallets': typeof AuthenticatedAppWalletsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/budgets': typeof AuthenticatedAppBudgetsRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/goals': typeof AuthenticatedAppGoalsRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/wallets': typeof AuthenticatedAppWalletsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/budgets': typeof AuthenticatedAppBudgetsRoute
  '/_authenticated/app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/app/goals': typeof AuthenticatedAppGoalsRoute
  '/_authenticated/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/_authenticated/app/wallets': typeof AuthenticatedAppWalletsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/app/analytics'
    | '/app/budgets'
    | '/app/coach'
    | '/app/goals'
    | '/app/transactions'
    | '/app/wallets'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/budgets'
    | '/app/coach'
    | '/app/goals'
    | '/app/transactions'
    | '/app/wallets'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/budgets'
    | '/_authenticated/app/coach'
    | '/_authenticated/app/goals'
    | '/_authenticated/app/transactions'
    | '/_authenticated/app/wallets'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wallets': {
      id: '/_authenticated/app/wallets'
      path: '/wallets'
      fullPath: '/app/wallets'
      preLoaderRoute: typeof AuthenticatedAppWalletsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transactions': {
      id: '/_authenticated/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/goals': {
      id: '/_authenticated/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AuthenticatedAppGoalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/coach': {
      id: '/_authenticated/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/budgets': {
      id: '/_authenticated/app/budgets'
      path: '/budgets'
      fullPath: '/app/budgets'
      preLoaderRoute: typeof AuthenticatedAppBudgetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppBudgetsRoute: typeof AuthenticatedAppBudgetsRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppGoalsRoute: typeof AuthenticatedAppGoalsRoute
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute
  AuthenticatedAppWalletsRoute: typeof AuthenticatedAppWalletsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppBudgetsRoute: AuthenticatedAppBudgetsRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppGoalsRoute: AuthenticatedAppGoalsRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
  AuthenticatedAppWalletsRoute: AuthenticatedAppWalletsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
